### Получение рецепта
GET http://localhost:8080/recipe
### Добавление рецепта 1
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "id": 1,
  " name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом ",
  " cookingTime": 7,
  " unitOfTime": " мин.",
  "ingredients ": [
    {
      " name": "Специи ",
      " quantity": 0,
      " unitOfMeasurement": " по вкусу"
    },
    {
      " name": "Консервированная фасоль",
      " quantity": 400,
      " unitOfMeasurement": " гр."
    },
    {
      " name": "Лимон",
      " quantity": 1,
      " unitOfMeasurement": " шт."
    },
    {
      " name": "Чеснок",
      " quantity": 2,
      " unitOfMeasurement": " зуб."
    },
    {
      " name": "Оливковое масло",
      " quantity": 50,
      " unitOfMeasurement": " мл."
    },
    {
      " name": "Рукола",
      " quantity": 100,
      " unitOfMeasurement": " гр."
    },
    {
      " name": "Творожный сыр",
      " quantity": 200,
      " unitOfMeasurement": " гр."
    },
{
" name": "Красный лук ",
" quantity": 50,
" unitOfMeasurement": " гр."
}],



  " cookingInstructions": {
    " 1 ": "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой. ",
    " 2 ": "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром.",
    " 3 ": "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  }
}

### Добавление рецепта 2
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "id": 2,
  " name": "Сырники из творога ",
  " cookingTime": 30,
  " unitOfTime": " мин.",
  "ingredients ": [
    {
      " name": "Творог ",
      " quantity": 350,
      " unitOfMeasurement": " гр."
    },
    {
      " name": "Куриное яйцо",
      " quantity": 2,
      " unitOfMeasurement": " шт."
    },
    {
      " name": "Пшеничная мука",
      " quantity": 6,
      " unitOfMeasurement": " ст.л."
    },
    {
      " name": "Сахар",
      " quantity": 2,
      " unitOfMeasurement": " ст.л."
    }
  ],
  " cookingInstructions": {
    " 1 ": "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте. ",
    " 2 ": "Всыпьте в творог муку и тщательно перемешайте.",
    " 3 ": "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    " 4 ": "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду. ",
    " 5 ": "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния. ",
    " 6 ": "Повторяйте, пока творог не закончится."
  }
}






